package view;

import controller.HocVienController;
import model.HocVien;

public class HocVienJFrame extends javax.swing.JFrame {

    /**
     * Creates new form HocVienJFrame
     */
    public HocVienJFrame(HocVien hocVien) {
        initComponents();
        
        HocVienController controller = new HocVienController(btnSubmit, jtfMaHocVien, jtfHoTen, jdcNgaySinh, jrdGioiTinhNam,
                jrdGioiTinhNu, jtfSdt, jtaDiaChi, jcbKichHoat,jlbMsg);
        controller.setView(hocVien);
        controller.setEvent();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupGioiTinh = new javax.swing.ButtonGroup();
        jpnLayout = new javax.swing.JPanel();
        btnSubmit = new javax.swing.JButton();
        jlbMsg = new javax.swing.JLabel();
        jpnThongTinHocVien = new javax.swing.JPanel();
        jlbMaHocVien = new javax.swing.JLabel();
        jlbHoTen = new javax.swing.JLabel();
        jlbNgaySinh = new javax.swing.JLabel();
        jlbGioiTinh = new javax.swing.JLabel();
        jlbTrangThai = new javax.swing.JLabel();
        jlbNote = new javax.swing.JLabel();
        jtfMaHocVien = new javax.swing.JTextField();
        jtfHoTen = new javax.swing.JTextField();
        jtfSdt = new javax.swing.JTextField();
        jdcNgaySinh = new com.toedter.calendar.JDateChooser();
        jcbKichHoat = new javax.swing.JCheckBox();
        jrdGioiTinhNam = new javax.swing.JRadioButton();
        jrdGioiTinhNu = new javax.swing.JRadioButton();
        jlbSdt = new javax.swing.JLabel();
        jlbDiaChi = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaDiaChi = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnSubmit.setBackground(new java.awt.Color(204, 0, 204));
        btnSubmit.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnSubmit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save.png"))); // NOI18N
        btnSubmit.setText("Lưu");

        jlbMsg.setBackground(new java.awt.Color(255, 3, 0));
        jlbMsg.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jlbMsg.setForeground(new java.awt.Color(255, 0, 0));

        jpnThongTinHocVien.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin học viên", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 1, 18), new java.awt.Color(1, 1, 1))); // NOI18N

        jlbMaHocVien.setText("Mã học viên");
        jlbMaHocVien.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        jlbHoTen.setText("Họ và tên");
        jlbHoTen.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        jlbNgaySinh.setText("Ngày sinh");
        jlbNgaySinh.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        jlbGioiTinh.setText("Giới tính");
        jlbGioiTinh.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        jlbTrangThai.setText("Trạng thái");
        jlbTrangThai.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        jlbNote.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jlbNote.setForeground(new java.awt.Color(255, 0, 0));
        jlbNote.setText("(*) Dữ liệu yêu cầu bắt buộc.");
        jlbNote.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        jdcNgaySinh.setDateFormatString("dd/MM/yyyy");

        jcbKichHoat.setText("Kích hoạt");

        btnGroupGioiTinh.add(jrdGioiTinhNam);
        jrdGioiTinhNam.setSelected(true);
        jrdGioiTinhNam.setText("Nam");

        btnGroupGioiTinh.add(jrdGioiTinhNu);
        jrdGioiTinhNu.setText("Nữ");

        jlbSdt.setText("Số điện thoại");
        jlbSdt.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        jlbDiaChi.setText("Địa chỉ");
        jlbDiaChi.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        jtaDiaChi.setColumns(20);
        jtaDiaChi.setLineWrap(true);
        jtaDiaChi.setRows(5);
        jtaDiaChi.setAutoscrolls(false);
        jScrollPane1.setViewportView(jtaDiaChi);

        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("(*)");

        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("(*)");

        javax.swing.GroupLayout jpnThongTinHocVienLayout = new javax.swing.GroupLayout(jpnThongTinHocVien);
        jpnThongTinHocVien.setLayout(jpnThongTinHocVienLayout);
        jpnThongTinHocVienLayout.setHorizontalGroup(
            jpnThongTinHocVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnThongTinHocVienLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnThongTinHocVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnThongTinHocVienLayout.createSequentialGroup()
                        .addGroup(jpnThongTinHocVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jlbHoTen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlbMaHocVien, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addGap(20, 20, 20)
                        .addGroup(jpnThongTinHocVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfMaHocVien, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfHoTen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jpnThongTinHocVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jpnThongTinHocVienLayout.createSequentialGroup()
                                .addComponent(jlbDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                            .addGroup(jpnThongTinHocVienLayout.createSequentialGroup()
                                .addComponent(jlbSdt, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jtfSdt, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(274, 274, 274))
                    .addGroup(jpnThongTinHocVienLayout.createSequentialGroup()
                        .addGroup(jpnThongTinHocVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpnThongTinHocVienLayout.createSequentialGroup()
                                .addComponent(jlbNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)
                                .addGap(20, 20, 20)
                                .addComponent(jdcNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpnThongTinHocVienLayout.createSequentialGroup()
                                .addComponent(jlbGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jrdGioiTinhNam)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jrdGioiTinhNu))
                            .addGroup(jpnThongTinHocVienLayout.createSequentialGroup()
                                .addComponent(jlbTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jcbKichHoat)))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(jpnThongTinHocVienLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jlbNote, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jpnThongTinHocVienLayout.setVerticalGroup(
            jpnThongTinHocVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnThongTinHocVienLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jpnThongTinHocVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbMaHocVien, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfMaHocVien, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfSdt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbSdt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jpnThongTinHocVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnThongTinHocVienLayout.createSequentialGroup()
                        .addGroup(jpnThongTinHocVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlbHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlbDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(33, 33, 33)
                        .addGroup(jpnThongTinHocVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpnThongTinHocVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jlbNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3))
                            .addComponent(jdcNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jpnThongTinHocVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jrdGioiTinhNam, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jrdGioiTinhNu, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(jpnThongTinHocVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbKichHoat, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jlbNote, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jpnLayoutLayout = new javax.swing.GroupLayout(jpnLayout);
        jpnLayout.setLayout(jpnLayoutLayout);
        jpnLayoutLayout.setHorizontalGroup(
            jpnLayoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnLayoutLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnLayoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpnThongTinHocVien, javax.swing.GroupLayout.PREFERRED_SIZE, 776, Short.MAX_VALUE)
                    .addGroup(jpnLayoutLayout.createSequentialGroup()
                        .addComponent(jlbMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 275, Short.MAX_VALUE)
                        .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jpnLayoutLayout.setVerticalGroup(
            jpnLayoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnLayoutLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jpnLayoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jpnThongTinHocVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jpnLayout, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnGroupGioiTinh;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JCheckBox jcbKichHoat;
    private com.toedter.calendar.JDateChooser jdcNgaySinh;
    private javax.swing.JLabel jlbDiaChi;
    private javax.swing.JLabel jlbGioiTinh;
    private javax.swing.JLabel jlbHoTen;
    private javax.swing.JLabel jlbMaHocVien;
    private javax.swing.JLabel jlbMsg;
    private javax.swing.JLabel jlbNgaySinh;
    private javax.swing.JLabel jlbNote;
    private javax.swing.JLabel jlbSdt;
    private javax.swing.JLabel jlbTrangThai;
    private javax.swing.JPanel jpnLayout;
    private javax.swing.JPanel jpnThongTinHocVien;
    private javax.swing.JRadioButton jrdGioiTinhNam;
    private javax.swing.JRadioButton jrdGioiTinhNu;
    private javax.swing.JTextArea jtaDiaChi;
    private javax.swing.JTextField jtfHoTen;
    private javax.swing.JTextField jtfMaHocVien;
    private javax.swing.JTextField jtfSdt;
    // End of variables declaration//GEN-END:variables

}
