package view;

import controller.HocVienController;
import controller.KhoaHocController;
import model.HocVien;
import model.KhoaHoc;

public class KhoaHocJFrame extends javax.swing.JFrame {

    /**
     * Creates new form HocVienJFrame
     */
    public KhoaHocJFrame(KhoaHoc khoaHoc) {
        initComponents();
        
        KhoaHocController controller = new KhoaHocController(btnSubmit, jtfMa3KhoaHoc, jtfTenKhoaHoc, jdcNgayBegin, jdcNgayEnd, jtfMoTa, jcbKichHoat, jlbMsg);
        
        controller.setView(khoaHoc);
        controller.setEvent();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupGioiTinh = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jpnLayout = new javax.swing.JPanel();
        btnSubmit = new javax.swing.JButton();
        jlbMsg = new javax.swing.JLabel();
        jpnThongTinKhoaHoc = new javax.swing.JPanel();
        jlbMaKhoaHoc = new javax.swing.JLabel();
        jlbTenKhoaHoc = new javax.swing.JLabel();
        jlbNgayBegin = new javax.swing.JLabel();
        jlbTrangThai = new javax.swing.JLabel();
        jlbNote = new javax.swing.JLabel();
        jtfMa3KhoaHoc = new javax.swing.JTextField();
        jtfTenKhoaHoc = new javax.swing.JTextField();
        jdcNgayBegin = new com.toedter.calendar.JDateChooser();
        jcbKichHoat = new javax.swing.JCheckBox();
        jlbMoTa = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jlbNgayEnd = new javax.swing.JLabel();
        jdcNgayEnd = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtfMoTa = new javax.swing.JTextArea();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnSubmit.setBackground(new java.awt.Color(204, 0, 204));
        btnSubmit.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnSubmit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save.png"))); // NOI18N
        btnSubmit.setText("Lưu");

        jlbMsg.setBackground(new java.awt.Color(255, 3, 0));
        jlbMsg.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jlbMsg.setForeground(new java.awt.Color(255, 0, 0));

        jpnThongTinKhoaHoc.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin khoá học", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 1, 18), new java.awt.Color(1, 1, 1))); // NOI18N

        jlbMaKhoaHoc.setText("Mã khoá học");
        jlbMaKhoaHoc.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        jlbTenKhoaHoc.setText("Tên khoá học");
        jlbTenKhoaHoc.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        jlbNgayBegin.setText("Ngày bắt đầu");
        jlbNgayBegin.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        jlbTrangThai.setText("Trạng thái");
        jlbTrangThai.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        jlbNote.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jlbNote.setForeground(new java.awt.Color(255, 0, 0));
        jlbNote.setText("(*) Dữ liệu yêu cầu bắt buộc.");
        jlbNote.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        jdcNgayBegin.setDateFormatString("dd/MM/yyyy");

        jcbKichHoat.setText("Kích hoạt");

        jlbMoTa.setText("Mô tả");
        jlbMoTa.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("(*)");

        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("(*)");

        jlbNgayEnd.setText("Ngày kết thúc");
        jlbNgayEnd.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        jdcNgayEnd.setDateFormatString("dd/MM/yyyy");

        jtfMoTa.setColumns(20);
        jtfMoTa.setForeground(new java.awt.Color(1, 1, 1));
        jtfMoTa.setRows(5);
        jtfMoTa.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane1.setViewportView(jtfMoTa);

        javax.swing.GroupLayout jpnThongTinKhoaHocLayout = new javax.swing.GroupLayout(jpnThongTinKhoaHoc);
        jpnThongTinKhoaHoc.setLayout(jpnThongTinKhoaHocLayout);
        jpnThongTinKhoaHocLayout.setHorizontalGroup(
            jpnThongTinKhoaHocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnThongTinKhoaHocLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnThongTinKhoaHocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnThongTinKhoaHocLayout.createSequentialGroup()
                        .addGroup(jpnThongTinKhoaHocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpnThongTinKhoaHocLayout.createSequentialGroup()
                                .addComponent(jlbNgayBegin, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)
                                .addGap(20, 20, 20)
                                .addComponent(jdcNgayBegin, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jlbNgayEnd, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jlbNote, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlbMoTa, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jpnThongTinKhoaHocLayout.createSequentialGroup()
                        .addGroup(jpnThongTinKhoaHocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpnThongTinKhoaHocLayout.createSequentialGroup()
                                .addGroup(jpnThongTinKhoaHocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jlbTenKhoaHoc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jlbMaKhoaHoc, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)
                                .addGap(20, 20, 20)
                                .addGroup(jpnThongTinKhoaHocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtfMa3KhoaHoc, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtfTenKhoaHoc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jlbTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jpnThongTinKhoaHocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jdcNgayEnd, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jcbKichHoat))))
                        .addGap(274, 274, 274))))
        );
        jpnThongTinKhoaHocLayout.setVerticalGroup(
            jpnThongTinKhoaHocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnThongTinKhoaHocLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jpnThongTinKhoaHocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jpnThongTinKhoaHocLayout.createSequentialGroup()
                        .addGroup(jpnThongTinKhoaHocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlbMaKhoaHoc, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfMa3KhoaHoc, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(jpnThongTinKhoaHocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlbTenKhoaHoc, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfTenKhoaHoc, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jlbTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcbKichHoat, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(jpnThongTinKhoaHocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpnThongTinKhoaHocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jlbNgayBegin, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3))
                            .addComponent(jdcNgayBegin, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlbNgayEnd, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jdcNgayEnd, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jlbMoTa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlbNote, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jpnLayoutLayout = new javax.swing.GroupLayout(jpnLayout);
        jpnLayout.setLayout(jpnLayoutLayout);
        jpnLayoutLayout.setHorizontalGroup(
            jpnLayoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnLayoutLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnLayoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpnThongTinKhoaHoc, javax.swing.GroupLayout.PREFERRED_SIZE, 776, Short.MAX_VALUE)
                    .addGroup(jpnLayoutLayout.createSequentialGroup()
                        .addComponent(jlbMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 275, Short.MAX_VALUE)
                        .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jpnLayoutLayout.setVerticalGroup(
            jpnLayoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnLayoutLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jpnLayoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jpnThongTinKhoaHoc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jpnThongTinKhoaHoc.getAccessibleContext().setAccessibleName("Thông tin khoá học");

        getContentPane().add(jpnLayout, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnGroupGioiTinh;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JCheckBox jcbKichHoat;
    private com.toedter.calendar.JDateChooser jdcNgayBegin;
    private com.toedter.calendar.JDateChooser jdcNgayEnd;
    private javax.swing.JLabel jlbMaKhoaHoc;
    private javax.swing.JLabel jlbMoTa;
    private javax.swing.JLabel jlbMsg;
    private javax.swing.JLabel jlbNgayBegin;
    private javax.swing.JLabel jlbNgayEnd;
    private javax.swing.JLabel jlbNote;
    private javax.swing.JLabel jlbTenKhoaHoc;
    private javax.swing.JLabel jlbTrangThai;
    private javax.swing.JPanel jpnLayout;
    private javax.swing.JPanel jpnThongTinKhoaHoc;
    private javax.swing.JTextField jtfMa3KhoaHoc;
    private javax.swing.JTextArea jtfMoTa;
    private javax.swing.JTextField jtfTenKhoaHoc;
    // End of variables declaration//GEN-END:variables

}
